.TH "Getargv" 3 "Version 0.1" "libgetargv++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Getargv \- This namespace isolates the library from your code\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBArgv\fP"
.br
.RI "This struct provides an iterable and printable representation of the arguments of the passed in pid, formatted as specified\&. "
.ti -1c
.RI "struct \fBArgvArgc\fP"
.br
.RI "This struct provides an iterable representation of the arguments of the passed in pid\&. "
.ti -1c
.RI "struct \fBIterator\fP"
.br
.RI "A template that turns a pointer to a C style array into a C++ contiguous iterator\&. "
.in -1c
.SH "Detailed Description"
.PP 
This namespace isolates the library from your code\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for libgetargv++ from the source code\&.
